# Generated by Django 3.1.7 on 2021-03-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'ordered'), (2, 'In transit'), (3, 'Delivered'), (4, 'Cancelled')], default=1),
        ),
    ]
